version: '3'

services:
  web-server:
    environment:
      DB_HOST: db-server
      DB_PORT: 5432
      PORT: 8080
      NODE_ENV: 'development'
    env_file:
      - docker.env
    depends_on:
      - db-server
    image: docker_image2:latest
    ports:
      - 8100:8080
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./public:/usr/src/server/public
  db-server:
    image: 'postgres:15.1-alpine3.16'
    env_file:
      - docker.env
    ports:
      - 15432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
