version: '2'

services:
  spark:
    image: docker.io/bitnami/spark
    user: root
    container_name: spark
    hostname: spark
    networks:
      dae:
        ipv4_address: 172.1.0.20
    environment:
      - PYTHONIOENCODING=utf8
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8077:8080'
      - '7077:7077'
    volumes:
      - ./dev:/opt/bitnami/spark/dev
  spark-worker-1:
    image: docker.io/bitnami/spark
    user: root
    container_name: spark-worker-1
    hostname: spark-worker-1
    networks:
      dae:
        ipv4_address: 172.1.0.21
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-2:
    image: docker.io/bitnami/spark
    user: root
    container_name: spark-worker-2
    hostname: spark-worker-2
    networks:
      dae:
        ipv4_address: 172.1.0.22
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  spark-worker-3:
    image: docker.io/bitnami/spark
    user: root
    container_name: spark-worker-3
    hostname: spark-worker-3
    networks:
      dae:
        ipv4_address: 172.1.0.23
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=3G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  dev_dae:
    external:
      name: dev_dae
