version: '2'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:4.0
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    networks:
      dev_dae:
        ipv4_address: 172.1.0.51
volumes:
  cassandra_data:
    driver: local

networks:
  dev_dae:
    external:
      name: dev_dae